### ISSUE TITLE
#1 SingleTable 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [tarlanhasanli/RDFBenchmarking#1]
SingleTable is a table of three 3 columns (Subject,Predicate,Object).
You are makingit just two columns !

**Comment by tarlanhasanli** [comment]
https://github.com/tarlanhasanli/RDFBenchmarking/blob/master/Datasets/CSV/SingleTable/SingleTable.csv

it is 3 columns, isn't it?

**Comment by MohamedRagabAnas** [comment]
yes, it is may be I overlooked it 👍
