### ISSUE TITLE
#2 PropertyTables files and VerticalTables files

### ISSUE THREAD

**Issue by MohamedRagabAnas** [tarlanhasanli/RDFBenchmarking#2]
Please Switch files files in these folders because you put vertical tables inside property tables and vice versa :)

**Comment by tarlanhasanli** [comment]
It is switched

**Comment by tarlanhasanli** [comment]
please pull again

**Comment by tarlanhasanli** [comment]
I think I misunderstood the process, I switched the files, please pull the latest version.
