### ISSUE TITLE
#4 Person Table is missing in PropertyTables 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [tarlanhasanli/RDFBenchmarking#4]
Person Table is missing in PropertyTables  !

**Comment by tarlanhasanli** [comment]
That's because there was no 'Person' in the Subject of Single table. Instead, we have a Reviewer table which has a type of Person.

**Comment by MohamedRagabAnas** [comment]
mmm, Are You Sure ?! Couldn't it be like a table that combine all types of "Person" as a subject, and the name, mbox, and country as other fields of the table ?!

example:

http://...../Reviwer1, "Tarlan", "mbox1", "Azeribgan"
http://..../Reviwer2,"Ragab","mbox2","Egypt"

**Comment by tarlanhasanli** [comment]
Yes, it is possible for sure but, the conversion from schema1 to schema3 is done automatically and the algorithm group data based on the subject not based on the predicate. 

For now, I will just rename the file. I think that could be the fastest solution.

**Comment by MohamedRagabAnas** [comment]
Sorry, didn't get what you mean

**Comment by tarlanhasanli** [comment]
The schema3 is created based on subjects for example, ...ProductFeature1, ...ProductFeature17, ...ProductFeature23, ...ProductFeature45, etc. I group these subjects into the productFeature.csv table based on the columns that were taken from the data model.

**Comment by MohamedRagabAnas** [comment]
I understand this, but renaming what file that will solve the propblem ?! :)

**Comment by tarlanhasanli** [comment]
Yes, for now, it is only one file and content is the same. I think I will do in that way until I come up with a better solution :))
